name: SAST Security Control

on:
  workflow_call:

jobs:
  sast:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Semgrep
        run: |
          python3 -m pip install --user semgrep
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        
      - name: Run SAST scan
        run: |
          semgrep scan \
            --config=auto \
            --sarif \
            --output=semgrep-results.sarif
        
      - name: Upload SAST results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sast-results
          path: semgrep-results.sarif