name: SAST Security Control

on:
  workflow_call:
    inputs:
      image:
        description: 'Docker image for SAST tool'
        required: false
        type: string
        default: 'docker.io/hijacksecurity/security/semgrep:latest'
      config:
        description: 'Configuration for the SAST tool'
        required: false
        type: string
        default: '--config=r/owasp-top-ten --config=r/cwe-top-25 --config=r/security-audit'

jobs:
  sast:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run SAST scan
        run: |
          # Create results directory
          mkdir -p results
          
          # Run SAST scan with SARIF output
          docker run --rm \
            -e SEMGREP_SEND_METRICS=off \
            -v "$GITHUB_WORKSPACE:/src" \
            -w /src \
            --user "$(id -u):$(id -g)" \
            ${{ inputs.image }} \
            semgrep scan \
              ${{ inputs.config }} \
              --sarif --output=results/sast-results.sarif || echo "SARIF generation completed with exit code $?"
            
          # Run SAST scan with JSON output  
          docker run --rm \
            -e SEMGREP_SEND_METRICS=off \
            -v "$GITHUB_WORKSPACE:/src" \
            -w /src \
            --user "$(id -u):$(id -g)" \
            ${{ inputs.image }} \
            semgrep scan \
              ${{ inputs.config }} \
              --json --output=results/sast-results.json || echo "JSON generation completed with exit code $?"
            
          # Run SAST scan with JUnit XML output
          docker run --rm \
            -e SEMGREP_SEND_METRICS=off \
            -v "$GITHUB_WORKSPACE:/src" \
            -w /src \
            --user "$(id -u):$(id -g)" \
            ${{ inputs.image }} \
            semgrep scan \
              ${{ inputs.config }} \
              --junit-xml --output=results/sast-results.xml || echo "JUnit XML generation completed with exit code $?"
        
      - name: Upload to GitHub Security tab
        if: always() && hashFiles('results/sast-results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results/sast-results.sarif
          category: sast
          
      - name: Publish JUnit Test Results
        if: always() && hashFiles('results/sast-results.xml') != ''
        uses: dorny/test-reporter@v1
        with:
          name: SAST Security Tests
          path: results/sast-results.xml
          reporter: java-junit
          
      - name: Upload SAST results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sast-results
          path: results/
          if-no-files-found: warn