name: SAST Security Control

on:
  workflow_call:

jobs:
  sast:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run SAST scan
        run: |
          # Run scans using Docker without root or ownership issues
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/src" \
            -w /src \
            docker.io/hijacksecurity/semgrep:latest \
            semgrep scan --config=auto --sarif --output=sast-results.sarif
            
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/src" \
            -w /src \
            docker.io/hijacksecurity/semgrep:latest \
            semgrep scan --config=auto --json --output=sast-results.json
            
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/src" \
            -w /src \
            docker.io/hijacksecurity/semgrep:latest \
            semgrep scan --config=auto --junit-xml --output=sast-results.xml
            
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/src" \
            -w /src \
            docker.io/hijacksecurity/semgrep:latest \
            semgrep scan --config=auto --output=sast-report.html --dataflow-traces || true
        
      - name: Upload to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sast-results.sarif
          category: sast
          
      - name: Publish JUnit Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: SAST Security Tests
          path: sast-results.xml
          reporter: java-junit
          
      - name: Upload SAST results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sast-results
          path: |
            sast-results.sarif
            sast-results.json
            sast-results.xml
            sast-report.html