name: SAST Security Control

on:
  workflow_call:

jobs:
  sast:
    runs-on: ubuntu-latest
    container:
      image: docker.io/hijacksecurity/semgrep:latest
      options: --user root
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run SAST scan
        run: |
          semgrep scan \
            --config="${SEMGREP_CONFIG:-p/security}" \
            --sarif \
            --output=semgrep-results.sarif \
            --metrics=off
        
      - name: Upload SARIF results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results.sarif
          category: sast