name: SCA Security Control

on:
  workflow_call:
    inputs:
      image:
        description: 'Docker image for SCA tool'
        required: false
        type: string
        default: 'semgrep/semgrep:latest'

jobs:
  SCAScan:
    name: SCA Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run SCA scan
        run: |
          # Create results directory
          mkdir -p results
          
          echo "Running OSS dependency scanning..."
          
          # Official semgrep image runs as root, custom images can use non-root
          USER_FLAG=""
          if [[ "${{ inputs.image }}" != *"semgrep/semgrep"* ]]; then
            USER_FLAG="--user $(id -u):$(id -g)"
          fi
          
          # Run dependency scanning with SARIF output
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/src" \
            -w /src \
            $USER_FLAG \
            ${{ inputs.image }} \
            semgrep scan \
              --config=r/python.lang.security.audit.dependencies \
              --config=r/javascript.lang.security.audit.dependencies \
              --config=r/ruby.lang.security.audit.dependencies \
              --config=r/java.lang.security.audit.dependencies \
              --config=r/go.lang.security.audit.dependencies \
              --config=r/csharp.lang.security.audit.dependencies \
              --sarif --output=results/sca-results.sarif || echo "SARIF scan completed with exit code $?"
              
          # Run dependency scanning with JSON output
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/src" \
            -w /src \
            $USER_FLAG \
            ${{ inputs.image }} \
            semgrep scan \
              --config=r/python.lang.security.audit.dependencies \
              --config=r/javascript.lang.security.audit.dependencies \
              --config=r/ruby.lang.security.audit.dependencies \
              --config=r/java.lang.security.audit.dependencies \
              --config=r/go.lang.security.audit.dependencies \
              --config=r/csharp.lang.security.audit.dependencies \
              --json --output=results/sca-results.json || echo "JSON scan completed with exit code $?"
          
          # Run dependency scanning with JUnit XML output
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/src" \
            -w /src \
            $USER_FLAG \
            ${{ inputs.image }} \
            semgrep scan \
              --config=r/python.lang.security.audit.dependencies \
              --config=r/javascript.lang.security.audit.dependencies \
              --config=r/ruby.lang.security.audit.dependencies \
              --config=r/java.lang.security.audit.dependencies \
              --config=r/go.lang.security.audit.dependencies \
              --config=r/csharp.lang.security.audit.dependencies \
              --junit-xml --output=results/sca-results.xml || echo "JUnit XML scan completed with exit code $?"
              
          # Run dependency scanning with HTML output
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/src" \
            -w /src \
            $USER_FLAG \
            ${{ inputs.image }} \
            semgrep scan \
              --config=r/python.lang.security.audit.dependencies \
              --config=r/javascript.lang.security.audit.dependencies \
              --config=r/ruby.lang.security.audit.dependencies \
              --config=r/java.lang.security.audit.dependencies \
              --config=r/go.lang.security.audit.dependencies \
              --config=r/csharp.lang.security.audit.dependencies \
              --dataflow-traces \
              --output=results/sca-report.html || echo "HTML report generation completed with exit code $?"
              
          # Fix permissions if running as root (official image)
          if [[ "${{ inputs.image }}" == *"semgrep/semgrep"* ]]; then
            sudo chown -R $(id -u):$(id -g) results/ || true
          fi
        
      - name: Upload to GitHub Security tab
        if: always() && hashFiles('results/sca-results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results/sca-results.sarif
          category: sca
          
          
      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sca-results
          path: results/
          if-no-files-found: warn