name: SCA Security Control

on:
  workflow_call:

jobs:
  sca:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Semgrep
        run: |
          python3 -m pip install --user semgrep
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        
      - name: Run SCA scan
        run: |
          semgrep scan \
            --config=r/generic.secrets \
            --config=r/secrets \
            --json \
            --output=sca-results.json
        
      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sca-results
          path: sca-results.json