name: SCA Security Control

on:
  workflow_call:

jobs:
  sca:
    runs-on: ubuntu-latest
    container:
      image: docker.io/hijacksecurity/semgrep:latest
      options: --user root
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Fix Git ownership
        run: git config --global --add safe.directory /__w/*/
        
      - name: Run SCA scan
        run: |
          # Generate standardized reports in all formats
          semgrep scan \
            --config=r/generic.secrets \
            --config=r/secrets \
            --sarif \
            --output=sca-results.sarif
            
          semgrep scan \
            --config=r/generic.secrets \
            --config=r/secrets \
            --json \
            --output=sca-results.json
            
          semgrep scan \
            --config=r/generic.secrets \
            --config=r/secrets \
            --junit-xml \
            --output=sca-results.xml
            
          semgrep scan \
            --config=r/generic.secrets \
            --config=r/secrets \
            --output=sca-report.html || true
        
      - name: Upload to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sca-results.sarif
          category: sca
          
      - name: Publish JUnit Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: SCA Security Tests
          path: sca-results.xml
          reporter: java-junit
          
      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sca-results
          path: |
            sca-results.sarif
            sca-results.json
            sca-results.xml
            sca-report.html