name: SCA Security Control

on:
  workflow_call:

jobs:
  sca:
    runs-on: ubuntu-latest
    container:
      image: docker.io/hijacksecurity/semgrep:latest
      options: --user root
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run SCA scan
        run: |
          # Generate multiple output formats
          semgrep scan \
            --config=r/generic.secrets \
            --config=r/secrets \
            --sarif \
            --output=sca-results.sarif
            
          semgrep scan \
            --config=r/generic.secrets \
            --config=r/secrets \
            --json \
            --output=sca-results.json
            
          # Generate HTML report for better viewing
          semgrep scan \
            --config=r/generic.secrets \
            --config=r/secrets \
            --output=sca-report.html || true
        
      - name: Upload to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sca-results.sarif
          category: sca
          
      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sca-results
          path: |
            sca-results.sarif
            sca-results.json
            sca-report.html